[build]
rustflags = [
"-C", "link-arg=-Wl,-T,/usr/local/rust/elf64-std.ld",
"-C", "link-arg=-no-pie"
]

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
strip = true
codegen-units = 1

[cargo-new]
vcs = "none"