(deftheme c
  "Created 2021-11-14.")

(custom-theme-set-faces
 'c
 '(default ((t (:background "#2f2f2f" :foreground "#dfdfdf" :family "cnxt"))))
 '(cursor ((t (:background "#ffff7f"))))
 '(fixed-pitch-serif ((t (:foreground "#ffffff"))))
 '(fixed-pitch ((t (:family "cnxt"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#ff9f9f"))))
 '(homoglyph ((t (:weight bold))))
 '(minibuffer-prompt ((t (:weight bold))))
 '(highlight ((t (:background "#4f4f4f" :box (:line-width 1 :color "#5f5f5f")))))
 '(region ((t (:extend t :background "#1f1f1f" ))))
 '(shadow ((t (:foreground "#7f7f7f"))))
 '(secondary-selection ((t (:extend t :background "#7f007f"))))
 '(trailing-whitespace ((t (:background "#7f5f5f"))))
 '(font-lock-builtin-face ((t (:foreground "#9f9fff" :weight bold))))
 '(font-lock-comment-delimiter-face ((t (:inherit nil :foreground "#6f6f6f"))))
 '(font-lock-comment-face ((t (:foreground "#8f8f8f"))))
 '(font-lock-constant-face ((t (:weight bold))))
 '(font-lock-doc-face ((t (:foreground "#af7f7f"))))
 '(font-lock-function-name-face ((t (:foreground "#afafff"))))
 '(font-lock-keyword-face ((t (:foreground "#5fff5f" :weight bold))))
 '(font-lock-negation-char-face ((t (:weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#7f7fff"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit bold))))
 '(font-lock-regexp-grouping-construct ((t (:inherit bold))))
 '(font-lock-string-face ((t (:foreground "#ff8f8f"))))
 '(font-lock-type-face ((t (:foreground "#ffbf5f"))))
 '(font-lock-variable-name-face ((t nil)))
 '(font-lock-warning-face ((t (:inherit error))))
 '(button ((t (:inherit link))))
 '(link ((t (:foreground "#9f9fff" :underline t))))
 '(link-visited ((t (:foreground "#df7fff" :underline t))))
 '(fringe ((t (:background "#5f5f5f" :foreground "#9f9f9f" :box (:line-width 2 :color "#5f5f5f")))))
 '(header-line ((t (:background "#666"))))
 '(tooltip ((t (:background "#6f6f6f"))))
 '(mode-line ((t (:background "#5f5f5f" :box (:line-width 2 :color "#5f5f5f")))))
 '(mode-line-buffer-id ((t (:foreground "#5fff5f" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "#555753" :foreground "#eeeeec" :box (:line-width -1 :style released-button)))))
 '(isearch ((t (:foreground "#eeeeec" :background "#ce5c00"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:background "#8f5902"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit isearch)))))

(provide-theme 'c)
